[build]
  command = "pip install -r requirements.txt && python netlify/functions/server.py"
  publish = "netlify/functions"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
