name: Deploy Flask App

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (adjust if you're using a different branch)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python3 -m pip3 install --upgrade pip3
          pip3 install -r requirements.txt

      # Step 4: Set GOOGLE_APPLICATION_CREDENTIALS environment variable
      - name: Set up Firebase credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > firebase_credentials.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # Step 5: Run Flask app or deploy (adjust the following command as needed)
      - name: Run Flask app
        run: |
          flask run  # Or use another command to start your Flask app

