jobs:
  setup_firebase_credentials:
    runs-on: ubuntu-latest

    steps:
      # Step: Set up Firebase credentials using the secret stored in GitHub
      - name: Set up Firebase credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > ./firebase-credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/firebase-credentials.json
