name: Firebase Credentials Setup

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch name
  pull_request:
    branches:
      - main  # or 'master', depending on your default branch name

jobs:
  setup_firebase_credentials:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Firebase credentials from GitHub secrets
      - name: Set up Firebase credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > ./firebase-credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/firebase-credentials.json
