name: Deploy Flask App

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Use Firebase Credentials stored in GitHub Secrets
    - name: Set up Firebase credentials as environment variable
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> $GITHUB_ENV

    # Step 2: Deploy your application here (for example, using Firebase CLI or other deployment methods)
    # You can add specific deployment actions here as per your needs.
